sudo: false
language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-3.2.3-20160803030038-a6a90e2.tar.gz | tar xz
- chmod ugo+x ci/*
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; set fork in Test := false; test; package; assembly'
- ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
after_script:
- rm -rf ci
before_install:
- openssl aes-256-cbc -K $encrypted_b4703176de36_key -iv $encrypted_b4703176de36_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
env:
  global:
  - secure: aEYAvf4FFobLe2YFLtitTeWHVFFYAcEuYfJvzTyRWlKPjysor/SWVQ2quJBLzvpUImDO4VoIXJLgBoujYi/DTiLT52gX+GTsDPJeflTLf4OxungFstFsUYs0lBXazPnfOAv96cOXoCP2LAjZVK58bYj+l421fKdt7btU2qgYusQ=
  - secure: NlOtfbOfsmUwE0TMOApRRKJbdBsC9fXb2PXtmgLYj9xEhX+1FuWb6hXtUPiN4iSFu1oLwR5uDOKGcSgZKSzPEPBItgbyrT/tMNH9VEyBUCaFLze1paZXMWyJmwaTpeHRPYE7SQ162PnWxt1YU5HAmYTXbxTD4VACIsHTJOM0ZPY=
